Author: Trần Minh Quân - 21130494

# Task1: Python programming

## Task 1.1: Find max/min, total, sort list, count positive/negative
Input:
+ An integer **n**
+ A list of integer numbers **x1, x2, ..., xn**

Output:
+ Print the maximum/minimum element in the given list
+ Print total values of the list
+ Print the list after sorted by ascending order
+ Print number of positive/negative

In [1]:
def printListInfo():
  print("Number of elements: ")
  n = int(input())
  if n <= 0:
    raise Exception("Number of elements must larger than 0")

  L = []
  for i in range(1, n + 1):
    print(f"Element {i}: ")
    element = int(input())
    L.append(element)

  print(f"Max: {max(L)}")
  print(f"Min: {min(L)}")
  print(f"Total values: {sum(L)}")
  print(f"List after sorted by ascending order: {sorted(L)}")
  print(f"Number of positive elements: {sum(1 for element in L if element > 0)}")
  print(f"Number of negative elements: {sum(1 for element in L if element < 0)}")

In [2]:
printListInfo()

Number of elements: 
10
Element 1: 
12
Element 2: 
3
Element 3: 
-5
Element 4: 
-8
Element 5: 
9
Element 6: 
6
Element 7: 
-11
Element 8: 
20
Element 9: 
-13
Element 10: 
1
Max: 20
Min: -13
Total values: 14
List after sorted by ascending order: [-13, -11, -8, -5, 1, 3, 6, 9, 12, 20]
Number of positive elements: 6
Number of negative elements: 4


## Task 1.2: Compute 1 + 1.2 + 1.2.3 + ...

In [3]:
def computeSpecialSum(n):
  if n <= 0:
    raise Exception("The given input must bigger than 0.")

  sum = 0
  currentOperand = 1
  for i in range(1,n + 1):
    currentOperand *= i
    sum += currentOperand

  return sum


In [4]:
print(computeSpecialSum(1))
print(computeSpecialSum(3))
print(computeSpecialSum(5))

1
9
153


## Task 1.3: OOP

Class **Post**

In [5]:
class Post():
  def __init__(self, content, subject, likes):
    self.content = content
    self.subject = subject
    self.likes = likes

Class **Account** and all childs (**VerifiedAccount**, **NormalAccount**)

In [6]:
class Account():
  def __init__(self, name, email, country, friends, posts):
    self.name = name
    self.email = email
    self.country = country
    self.friends = friends
    self.posts = posts

  # Get the highest number of likes in posts
  def getMaxLike(self):
    return max(post.likes for post in self.posts)

  # Find the account having the post with the highest likes from the list of friends
  def getMaxLikePostByFriend(self):
    maxLike = -1;
    account = None;
    for friend in self.friends:
      if friend.getMaxLike() > maxLike:
        maxLike = friend.getMaxLike()
        account = friend
    return account

  def toString(self):
      return f"Name: {self.name}, Country: {self.country}, NumFriends: {len(self.friends)}, NumPosts: {len(self.posts)}, MaxLike: {self.getMaxLike()}"

  def __str__(self):
    return f"[{self.toString()}]"

In [7]:
class NormalAccount(Account):
    def __init__(self, name, email, country, friends, posts):
        super().__init__(name=name, email=email, country=country, friends=friends, posts=posts)

    def __str__(self):
        return f"[Type: Normal, {self.toString()}]"

In [8]:
class VerifiedAccount(Account):
    def __init__(self, name, email, country, friends, posts, fromDate):
        self.fromDate = fromDate
        super().__init__(name=name, email=email, country=country, friends=friends, posts=posts)

    def __str__(self):
        return f"[Type: Verified, {self.toString()}, fromDate: {self.fromDate}]"

Class **AccountManager**

In [9]:
class AccountManager():
  def __init__(self, accounts):
    self.accounts = accounts

  def groupAccountsByPostLike(self):
    groups = {False: [], True: []}
    for account in self.accounts:
      if len(account.posts) < 10:
        groups[False].append(account)
      else:
        groups[True].append(account)
    return groups

  def filterAccounts(self, country):
    accountsByCountry = filter(lambda account: account.country == country, self.accounts)
    return sorted(accountsByCountry, key=lambda account: (-len(account.posts), account.name))

  def __str__(self):
    result = "[\n"
    for account in self.accounts:
      result += account.__str__() + ", \n"
    result += "]"
    return result

Additional function: generate tests

In [10]:
from random import randint, random, seed
from datetime import datetime

seed(999) # Special seed, make the result consitent for every time we run.

def generate_fake_data(numAccounts, rangePosts, rangeLikes, rangeFriends):
    accounts = []
    firstNames = ["Alice", "Benjamin", "Catherine", "Dylan", "Eva", "Felix", "Grace", "Harrison", "Isabel", "Jacob"]
    lastNames = ["Anderson", "Baxter", "Cruz", "Dixon", "Ellis", "Fleming", "Garcia", "Hawkins", "Ingram", "Johnson"]
    countries = ["Australia", "Brazil", "Canada", "Denmark", "Egypt", "France", "Germany", "India", "Japan", "Kenya"]
    probVerified = 0.2;
    # Create random account profile
    for i in range(numAccounts):
        firstName = firstNames[randint(0, len(firstNames) - 1)]
        lastName = lastNames[randint(0, len(lastNames) - 1)]
        name = firstName + " " + lastName
        email = firstName.lower() + "_" + lastName.lower() +"@gmail.com"
        country = countries[randint(0, len(countries) - 1)]
        numPost = randint(rangePosts[0], rangePosts[1])
        posts = []
        # Create random posts
        for j in range(numPost):
            likes = randint(rangeLikes[0], rangeLikes[1])
            posts.append(Post(content="Temp content", subject="Temp subject", likes=likes))
        #Make account becomes Verified (20%) or just Normal (80%)
        if(random() < 0.2):
            fromDate = datetime(randint(2018, 2024), randint(1, 12), randint(1, 28))
            accounts.append(VerifiedAccount(name=name, email=email, country=country, friends=[], posts=posts, fromDate=fromDate))
        else:
            accounts.append(NormalAccount(name=name, email=email, country=country, friends=[], posts=posts))


    # Make all accounts in the list have friends
    for accountIndex in range(len(accounts)):
        account = accounts[accountIndex]
        numFriends = randint(rangeFriends[0], rangeFriends[1])
        currentFriends = 0
        while currentFriends < numFriends:
            otherAccountIndex = randint(0, len(accounts) - 1)
            if(otherAccountIndex != i):
                currentFriends += 1
                account.friends.append(accounts[otherAccountIndex])

    return AccountManager(accounts=accounts)

In [11]:
def printList(list):
    for element in list:
        print(element)

In [12]:
account_manager = generate_fake_data(numAccounts=20, rangePosts=[1, 20], rangeLikes=[0, 100], rangeFriends=[1,5])

Show all accounts

In [13]:
print(account_manager)

[
[Type: Normal, Name: Benjamin Johnson, Country: Kenya, NumFriends: 3, NumPosts: 18, MaxLike: 99], 
[Type: Normal, Name: Dylan Garcia, Country: Brazil, NumFriends: 3, NumPosts: 9, MaxLike: 86], 
[Type: Normal, Name: Benjamin Ingram, Country: Kenya, NumFriends: 3, NumPosts: 15, MaxLike: 95], 
[Type: Normal, Name: Eva Ingram, Country: France, NumFriends: 4, NumPosts: 2, MaxLike: 98], 
[Type: Normal, Name: Benjamin Garcia, Country: Kenya, NumFriends: 1, NumPosts: 18, MaxLike: 80], 
[Type: Normal, Name: Benjamin Garcia, Country: Kenya, NumFriends: 2, NumPosts: 4, MaxLike: 89], 
[Type: Normal, Name: Harrison Anderson, Country: Kenya, NumFriends: 3, NumPosts: 15, MaxLike: 100], 
[Type: Normal, Name: Grace Cruz, Country: India, NumFriends: 3, NumPosts: 18, MaxLike: 99], 
[Type: Normal, Name: Jacob Hawkins, Country: Japan, NumFriends: 5, NumPosts: 1, MaxLike: 49], 
[Type: Normal, Name: Isabel Fleming, Country: Kenya, NumFriends: 3, NumPosts: 5, MaxLike: 57], 
[Type: Normal, Name: Alice Ingram

Test **getMaxLikePostByFriend()**

In [14]:
account = account_manager.accounts[0]
print("Friends list: ")
printList(account.friends)
print("----------------------------------")
print("The friend who have highest likes:")
print(account.getMaxLikePostByFriend())

Friends list: 
[Type: Normal, Name: Benjamin Ingram, Country: Kenya, NumFriends: 3, NumPosts: 15, MaxLike: 95]
[Type: Normal, Name: Benjamin Garcia, Country: Kenya, NumFriends: 1, NumPosts: 18, MaxLike: 80]
[Type: Normal, Name: Grace Cruz, Country: India, NumFriends: 3, NumPosts: 18, MaxLike: 99]
----------------------------------
The friend who have highest likes:
[Type: Normal, Name: Grace Cruz, Country: India, NumFriends: 3, NumPosts: 18, MaxLike: 99]


Test **groupAccountsByPostLike()**

In [15]:
groups = account_manager.groupAccountsByPostLike()
print("Less than 10 posts")
printList(groups[False])
print("-----------------------------------------------")
print("Equal or more than 10 posts")
printList(groups[True])

Less than 10 posts
[Type: Normal, Name: Dylan Garcia, Country: Brazil, NumFriends: 3, NumPosts: 9, MaxLike: 86]
[Type: Normal, Name: Eva Ingram, Country: France, NumFriends: 4, NumPosts: 2, MaxLike: 98]
[Type: Normal, Name: Benjamin Garcia, Country: Kenya, NumFriends: 2, NumPosts: 4, MaxLike: 89]
[Type: Normal, Name: Jacob Hawkins, Country: Japan, NumFriends: 5, NumPosts: 1, MaxLike: 49]
[Type: Normal, Name: Isabel Fleming, Country: Kenya, NumFriends: 3, NumPosts: 5, MaxLike: 57]
[Type: Normal, Name: Felix Cruz, Country: Australia, NumFriends: 3, NumPosts: 8, MaxLike: 98]
[Type: Normal, Name: Isabel Garcia, Country: France, NumFriends: 3, NumPosts: 6, MaxLike: 99]
[Type: Verified, Name: Grace Johnson, Country: Japan, NumFriends: 5, NumPosts: 9, MaxLike: 95, fromDate: 2021-03-04 00:00:00]
[Type: Verified, Name: Catherine Dixon, Country: Japan, NumFriends: 2, NumPosts: 1, MaxLike: 83, fromDate: 2023-09-14 00:00:00]
-----------------------------------------------
Equal or more than 10 pos

Test **filterAccounts(country)**

In [16]:
for account in account_manager.filterAccounts(country="Kenya"):
    print(account)

[Type: Normal, Name: Benjamin Garcia, Country: Kenya, NumFriends: 1, NumPosts: 18, MaxLike: 80]
[Type: Normal, Name: Benjamin Johnson, Country: Kenya, NumFriends: 3, NumPosts: 18, MaxLike: 99]
[Type: Normal, Name: Benjamin Ingram, Country: Kenya, NumFriends: 3, NumPosts: 15, MaxLike: 95]
[Type: Normal, Name: Harrison Anderson, Country: Kenya, NumFriends: 3, NumPosts: 15, MaxLike: 100]
[Type: Normal, Name: Grace Anderson, Country: Kenya, NumFriends: 2, NumPosts: 10, MaxLike: 95]
[Type: Normal, Name: Isabel Fleming, Country: Kenya, NumFriends: 3, NumPosts: 5, MaxLike: 57]
[Type: Normal, Name: Benjamin Garcia, Country: Kenya, NumFriends: 2, NumPosts: 4, MaxLike: 89]


# Task 2: NumPy

## Task 2.1: Arange array and reverse it

In [17]:
import numpy as np

def arangeAndReverse():
    return np.flip(np.arange(10, 25 + 1, 1))

In [18]:
print(arangeAndReverse())

[25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


## Task 2.2: Repeating array

In [19]:
def repeatingArray(arr, times):
    return np.tile(arr, times)

In [20]:
repeatingArray([1,9,7,5], 5)

array([1, 9, 7, 5, 1, 9, 7, 5, 1, 9, 7, 5, 1, 9, 7, 5, 1, 9, 7, 5])

## Task 2.3: Replace some elements by specific value

In [21]:
def replace(matrix, threshold):
    matrix[matrix > threshold] = threshold

In [22]:
matrix = np.array([[0.42, 0.48, 0.32],[0.74, 0.58, 0.38],[0.51, 0.34, 0.15]])
replace(matrix, 0.5)
matrix

array([[0.42, 0.48, 0.32],
       [0.5 , 0.5 , 0.38],
       [0.5 , 0.34, 0.15]])